data:
  datapath: 'data/NS_fine_Re500_S2048_s64_T500_t128.npy'
  Re: 500
  total_num: 500
  offset: 0
  n_sample: 1000
  time_interval: 0.5
  nx: 64
  nt: 128
  sub: 1
  sub_t: 1
  shuffle: True

model:
  layers: [32, 32, 32, 32, 32]
  modes1: [20, 20, 20, 20]
  modes2: [20, 20, 20, 20]
  modes3: [20, 20, 20, 20]
  fc_dim: 128

train:
  batchsize: 1
  epochs: 100
  milestones: [25, 50, 75]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 1.0
  f_loss: 1.0
  xy_loss: 5.0
  save_dir: 'Re500-FDM'
  save_name: 'PINO-pretrain-T500-05s.pt'

others:
  project: 'PINO-pretrain'
  group: 'Re500-0.5s'




