data:
  name: 'Burgers-0000'
  # datapath: 'data/Burger.mat'
  total_num: 1000
  offset: 900
  n_sample: 100
  nx: 128
  nt: 100
  sub: 1
  sub_t: 1

model:
  layers: [16, 24, 24, 32, 32]
  modes1: [15, 12, 9, 9]
  modes2: [15, 12, 9, 9]
  fc_dim: 128
  activation: gelu

train:
  batchsize: 20
  epochs: 500
  milestones: [150, 300, 450]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 10.0
  f_loss: 1.0
  xy_loss: 0.0
  save_dir: 'Burgers'
  save_name: 'burgers-eqn.pt'

log:
  project: 'PINO-burgers'
  group: 'train-0000'


test:
  batchsize: 1
  ckpt: 'checkpoints/Burgers/burgers-eqn.pt'

